### ISSUE TITLE
Default duration for to()

### ISSUE THREAD

**Issue by gingerbeardman** [NicMagnier/PlaydateSequence#4]
It would be great to have defaults for to() that make it obvious things are working.

Whenever I use sequence, I always wonder why it's not working and it's because I forgot to set the options on to() which I almost always do.

Looking at the code to make some personal changes easing has a good sensible default (inOutQuad) but duration has a unexpected default (zero) which makes the results surprising as it appears to not be working.

Might be a small thing but I think it would help onboarding.

Just a thought!

**Comment by NicMagnier** [comment]
good idea. Originally the goal was to use to(value) to also direct set the value directly. But later I've added set() that does that more clearly. I also added a new default duration for sleep()
